server:
  port: 9002
spring:
  application:
    name: scms-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7000.com:7000/eureka,http://www.eureka7001.com:7001/eureka,http://www.eureka7003.com:7003/eureka

zuul:
  routes:
    atguigu.serviceId: atguigu-scms-hystrix-dept
    atguigu.path: /atguigu-demo/**

