server:
  port: 8004
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.atguigu.cloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/*Mapper.xml

spring:
  application:
    name: Atguigu-SCMS-Hystrix-Dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #   mysql8.0用法
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_db_one?serverTimezone=UTC
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka